# Generated by Django 3.2.18 on 2023-10-11 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('info_text', models.TextField(default=None, verbose_name='文本')),
                ('url', models.CharField(default=None, max_length=64, verbose_name='url(文本二选一填写)')),
                ('info_type', models.CharField(choices=[(1, '文本'), (2, '超链接')], max_length=32, verbose_name='信息类型')),
            ],
        ),
        migrations.CreateModel(
            name='usr_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='账号名')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='usr_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 30, 3, 406033), verbose_name='访问时间')),
                ('ip', models.CharField(max_length=32, verbose_name='ip地址')),
                ('ua', models.TextField(verbose_name='UA')),
                ('title_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.info', verbose_name='标题')),
            ],
        ),
    ]
