# Generated by Django 3.2.18 on 2023-10-11 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 31, 29, 180834), verbose_name='访问时间'),
        ),
    ]
