# Generated by Django 3.2.18 on 2023-10-11 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_alter_usr_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 32, 34, 69416), verbose_name='访问时间'),
        ),
    ]
