# Generated by Django 3.2.18 on 2023-10-11 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_usr_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='访问时间'),
        ),
    ]
