# Generated by Django 3.2.18 on 2023-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_alter_usr_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_text',
            field=models.TextField(default=None, null=True, verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='info',
            name='info_type',
            field=models.SmallIntegerField(choices=[(1, '文本'), (2, '超链接')], verbose_name='信息类型'),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='url(文本二选一填写)'),
        ),
    ]
