# Generated by Django 3.2.18 on 2023-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_auto_20231011_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='url(文本二选一填写)'),
        ),
    ]
