# Generated by Django 3.2.18 on 2023-10-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='url(文本二选一填写)'),
        ),
    ]
