# Generated by Django 3.2.18 on 2023-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_auto_20231011_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_log',
            name='title_info',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
    ]
